cloud-gov/legacy-domain-certificate-renewer

docker/Dockerfile.dev

update for bullseye

---

ci/pipeline.yml
manifest.yml
pip-tools/dev-requirements.in
pip-tools/dev-requirements.txt
pip-tools/requirements.in
renewer/config.py
renewer/db.py
renewer/extensions.py
renewer/models.py
requirements.txt
tests/conftest.py
tests/lib/database.py
tests/unit/test_alb_db.py
tests/unit/test_cdn_db.py
tests/unit/test_config.py

- Add db, models, and supporting boilerplate. This is virtually all copy-paste from the migrator
None

Add db, models, and supporting boilerplate

---

renewer/__main__.py
renewer/cdn_models.py
renewer/config.py
renewer/db.py
renewer/domain_models.py
tests/lib/database.py
tests/unit/test_alb_db.py
tests/unit/test_cdn_db.py
tests/unit/test_config.py

- find active ALB instances
- method to check if an instance is ready for renewal
- refactor models into separate files, since we're going for thick models 
None

Find alb instances

---

.gitignore
dev
docker/serve
migrations/README
migrations/alembic.ini
migrations/env.py
migrations/script.py.mako
migrations/versions/cf25238724b3_initial_state.py
pip-tools/dev-requirements.txt
pip-tools/requirements.in
renewer/cdn_models.py
renewer/config.py
renewer/domain_models.py
requirements.txt

- Add alembic to track db changes
- Update models to match existing state more closely, so we don't get unwanted alembic changes
None

add alembic

---

renewer/aws.py
renewer/config.py
renewer/extensions.py
tests/unit/test_config.py

- Add testing around imports for upgrade config
- Set AWS region, even when we're not using it
None

Upgrade schema config again

---

ci/pipeline.yml

- fix creds param to staging and prod redis steps
None

fix creds param to staging and prod redis steps

---

pip-tools/dev-requirements.txt
pip-tools/requirements.in
renewer/huey.py
requirements.txt

make huey importable

---

renewer/config.py
tests/unit/test_config.py

- check that huey can start for real
None

check that huey can start for real

---

scripts/run-worker

- reference huey.huey, not just huey
- 
- 
None

more hueys!

---

ci/pipeline.yml

- pass lets encrypt email param correctly
None

pass lets encrypt email param correctly

---

docker/Dockerfile.dev
docker/start-servers.sh
docker/stop-servers.sh
renewer/config.py
renewer/huey.py
renewer/tasks/migrations.py
tests/conftest.py
tests/integration/test_alb_backport.py
tests/lib/tasks.py
tests/redis.conf

- start running backports in huey
- add test fixtures for huey testing
None

start running backports in huey

---

ci/pipeline.yml
dev
docker/mypy
pip-tools/dev-requirements.in
pip-tools/dev-requirements.txt
pyproject.toml
renewer/cdn_models.py
renewer/domain_models.py

- add mypy support and run mypy in pipeline. This is currently a very permissive mypy setup, but we can iterate on it
None

add mypy support and run mypy in pipeline

---

renewer/cdn_models.py
renewer/domain_models.py
renewer/route_type.py
renewer/tasks/letsencrypt.py
tests/integration/test_alb_letsencrypt_user.py
tests/integration/test_cdn_letsencrypt_user.py

- refactor tasks to support cdn and alb instances
None

refactor tasks to support cdn and alb instances

---

renewer/cdn_models.py
renewer/domain_models.py

- add annotations for non-inferrable sqlalchemy types
None

add annotations for non-inferrable sqlalchemy types

---

pip-tools/dev-requirements.txt
renewer/huey.py
renewer/tasks/letsencrypt.py

- Add annotations for mypy
- change imports for mypy
None

Add annotations for mypy, change imports for mypy

---

ci/pipeline.yml
renewer/aws.py
renewer/config.py
renewer/tasks/s3.py
tests/conftest.py
tests/integration/test_alb_renewal.py
tests/integration/test_cdn_renewal.py
tests/lib/fake_s3.py
tests/unit/test_config.py

- upload challenge files to S3
- add s3 commercial config
- add s3 test fixtures
None

upload challenge files to S3

---

renewer/consumer.py
scripts/run-worker

- add dedicated huey consumer module
None

add dedicated huey consumer module

---

renewer/tasks/alb.py
tests/integration/test_alb_renewal.py

- add functions to rotate ALB certs
None

add functions to rotate ALB certs

---

renewer/tasks/migrations.py
tests/integration/test_alb_backport.py

don't commit Nones

---

ci/pipeline.yml
renewer/config.py
renewer/tasks/alb.py
renewer/tasks/cdn.py
renewer/tasks/iam.py
tests/integration/test_alb_renewal.py
tests/integration/test_cdn_renewal.py
tests/lib/cdn_fixtures.py
tests/lib/fake_cloudfront.py
tests/unit/test_config.py

- Add function to remove old certificate
- add function to wait before removing old certificate
None

remove old certificates when done

---

renewer/models/domain.py
tests/integration/test_alb_backport.py
tests/lib/fake_iam.py
tests/unit/test_alb_db.py

- fix return types for get_server_certificate
None

fix return types for get_server_certificate

---

renewer/consumer.py

run renewals

---

renewer/json_log.py
renewer/models/common.py
renewer/tasks/alb.py
renewer/tasks/cdn.py
renewer/tasks/iam.py
renewer/tasks/letsencrypt.py
renewer/tasks/migrations.py
renewer/tasks/renewals.py

- add more logging statements and a logging helper. There's probably a better way to do the json, but this is good enough for this small app
None

add more logging statements and a logging helper

---

renewer/tasks/s3.py
tests/integration/test_alb_renewal.py
tests/integration/test_cdn_renewal.py

- remove duplicate slash from s3 PUT operation
None

remove duplicate slash from s3 PUT operation

---

ci/pipeline.yml
docker/start-servers.sh
docker/stop-servers.sh
renewer/config.py
renewer/huey.py
renewer/smtp.py
renewer/tasks/renewals.py
renewer/tasks/update_operations.py
tests/integration/test_alb_renewal.py
tests/integration/test_cdn_renewal.py
tests/integration/test_failing_tasks.py
tests/lib/tasks.py
tests/unit/test_config.py

- Track task state through failure or completion
- alert on failed tasks
None

Failing task alerts

---

renewer/models/cdn.py
tests/unit/test_cdn_db.py

- fix lazy-load bug on get user function
None

fix lazy-load bug on get user function

---

ci/pipeline.yml
renewer/config.py
renewer/consumer.py
renewer/db.py
renewer/huey.py
renewer/tasks/alb.py
renewer/tasks/cdn.py

- add logging to db open/close
- drop sessions for waiting tasks
None

Recycle sessions sometimes

---

renewer/suppress.py
renewer/tasks/cdn.py

- silence waiter errors - we don't care about the body of the error, but we do want Huey to see that an exception was raised
None

silence waiter errors

---

ci/pipeline.yml

- Update to new CF Resource + hardened ones
- For any logging statements, is there any chance that they could be logging sensitive data?
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of sensitive data.
This improves our stance by using hardened resources

Update to new CF Resource + hardened ones

---

dev
pip-tools/dev-requirements.txt
requirements.txt

- Update certifi>=2024.07.04
- Update urllib3 to 2.2.2
- For any logging statements, is there any chance that they could be logging sensitive data?
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of sensitive data.
Addresses active security alerts

Update deps to address security alerts

---

ci/pipeline.yml
dev
docker/Dockerfile.dev
pyproject.toml

- Updates docker image to use our hardened base image
- Fix target python version in pyproject.toml file
- Update pipeline to use new hardened image
- For any logging statements, is there any chance that they could be logging sensitive data?
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of sensitive data.
Updates pipeline to use hardened images. The new testing image is in ECR, so this should roll through with no issues.

Setup hardened image

---

ci/pipeline.yml

- Missed adding the get to the task
- For any logging statements, is there any chance that they could be logging sensitive data?
- Are log statements using a logging library with a logging level set? Setting a logging level means that log statements "below" that level will not be written to the output. For example, if the logging level is set to `INFO` and debugging statements are written with `log.debug` or similar, then they won't be written to the otput, which can prevent unintentional leaks of sensitive data.
Adds missing get

add missing get
